language: ruby
cache: bundler
rvm:
  - 2.5
script: 'bundle exec rake spec'
#matrix:
#  include:
#    - rvm: 1.9.3
#      script: bundle exec rake spec
#    - rvm: 2.0
#      script: bundle exec rake spec
#    - rvm: 2.1
#      script: bundle exec rake spec
#    - rvm: 2.2
#      script: bundle exec rake spec
#    - rvm: 2.3
#      script: bundle exec rake spec
#    - rvm: 2.4
#      script: bundle exec rake spec
#    - rvm: 2.5
#      script: bundle exec rake spec
